[package]
name = "lime-rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
eggmock = { path = "../../eggmock" }
rustc-hash = "2.1.0"
bv = "0.11.1"

[build-dependencies]
eggmock = { path = "../../eggmock" }