[package]
name = "lime-rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
eggmock = { path = "../../eggmock" }

[build-dependencies]
eggmock = { path = "../../eggmock" }